name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      
    # edit Libraries.IO.SDK.csproj to replace with desired version
    - name: replace version
      uses: jacobtomlinson/gha-find-replace@3.0.3
      with:
        include: "*/Libraries.IO.SDK/Libraries.IO.SDK.csproj"
        find: <Version>1.0.0</Version>
        replace: <Version>$RELEASE_VERSION</Version>
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack .\src\Libraries.IO.SDK

    # temp - store artifact / placeholder for uploading to Nuget
    - name: Archive package
      uses: actions/upload-artifact@v4
      with:
        name: Libraries.IO.SDK.nupkg
        path: .\src\Libraries.IO.SDK\bin\Release\Libraries.IO.SDK.*.nupkg
