name: release

on:
  release:
    types:
      - edited
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # get version from tag (e.g., v1.2.3 --> 1.2.3)
    - name: Get version
      id: get_version
      uses: JanneMattila/get-version-from-tag@22de24a56e53ef11268538c9e6a77659a142afa7 # v4

    - name: Display version
      run: |
        VERSION=$(echo "${{ steps.get_version.outputs.version }}")
        echo $VERSION
              
    # edit Libraries.IO.SDK.csproj to replace with desired version
    - name: Replace version
      uses: jacobtomlinson/gha-find-replace@dfbfef71bc27c27c39d89534540a8960e0eee6b0 # v3.0.5
      with:
        include: "*/Libraries.IO.SDK/Libraries.IO.SDK.csproj"
        find: <Version>1.0.0</Version>
        replace: <Version>${{ steps.get_version.outputs.version }}</Version>

    # build our library, run tests, and create the NuGet package
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore 
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack /home/runner/work/Libraries.IO.SDK/Libraries.IO.SDK/src/Libraries.IO.SDK/Libraries.IO.SDK.csproj

    # Publish package to NuGet
    - name: Publish to Nuget
      run: dotnet nuget push **\*.nupkg -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_API_KEY}}
      