name: release

on:
  release:
    types:
      - edited
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # get version from tag (e.g., v1.2.3 --> 1.2.3
    - name: Get version
      id: get_version
      uses: JanneMattila/get-version-from-tag@v3

    - name: Display version
      run: |
        VERSION=$(echo "${{ steps.get_version.outputs.version }}")
        echo $VERSION
              
    # edit Libraries.IO.SDK.csproj to replace with desired version
    - name: Replace version
      uses: jacobtomlinson/gha-find-replace@3.0.3
      with:
        include: "*/Libraries.IO.SDK/Libraries.IO.SDK.csproj"
        find: <Version>1.0.0</Version>
        replace: <Version>${{ steps.get_version.outputs.version }}</Version>
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack ./Libraries.IO.SDK/src/Libraries.IO.SDK/
